# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dcsZtoMJj2tM1jrR_wLKR3KqHSEbST3E
"""


import chart_studio.plotly as py
import plotly.figure_factory as ff
import numpy as np
import pandas as pd
import plotly.graph_objs as go
import plotly

import re

data = pd.read_csv('/content/lending_club_loan_two.csv')

data

data.issue_d

data.issue_d = pd.to_datetime(data.issue_d, format = '%b-%Y')

data.issue_d

data['year'] = data.issue_d.dt.year

data.head()

# Regex pattern to extract states (assuming a two-letter state code)
pattern = r'\b([A-Z]{2})\b'

# Extract states from addresses
states = [re.search(pattern, address).group(1) if re.search(pattern, address) else None for address in data.address]

# Create a new column with extracted states
data['state'] = states

data['state']

data['state'].isnull().sum()

# Assuming 'data' is a pandas DataFrame
data['id'] = range(1, len(data) + 1)

data

num_borrowers_in_state = data.groupby(['state'])['id'].count().reset_index()

num_borrowers_in_state

# Assuming 'data' is a pandas DataFrame and 'column_name' is the column you want to sum
column_sum = num_borrowers_in_state['id'].sum()
column_sum
# print("Sum of", num_borrowers_in_state, "column:", column_sum)

# Assuming 'data' is a pandas DataFrame and 'current_name' is the current name of the column
# and 'new_name' is the desired new name of the column
num_borrowers_in_state.rename(columns={'id': 'borrowers_in_country'}, inplace=True)

num_borrowers_in_state

import chart_studio

# chart_studio.tools.set_credentials_file(username='Ipasc', api_key='AWhZFAqOEvgmZgrkEMW5')

# import chart_studio.plotly as py
# import plotly.graph_objs as go

# d = [dict(
#     type='choropleth',
#     locations=num_borrowers_in_state['state'],
#     locationmode='USA-states',
#     z=num_borrowers_in_state['borrowers_in_country'],  # Assuming 'num_borrowers' is the correct column name
#     text=num_borrowers_in_state['state'],
#     autocolorscale=True,
#     reversescale=False,
#     marker=dict(
#         line=dict(
#             color='rgb(180,180,180)',
#             width=0.5
#         )),
#     colorbar=dict(
#         dtick=1,  # Replace autotick with dtick
#         title='Loan Quantity'),
# )]

# layout = dict(
#     title='States Loan Quantity From 2007 to 2015<br>Source: Kaggle',
#     geo=dict(
#         scope='usa',
#         showframe=False,
#         showcoastlines=True,
#         projection=dict(
#             type='mercator'
#         )
#     )
# )

# fig = go.Figure(data=d, layout=layout)
# py.iplot(fig, validate=False, filename='state-loanquantity')

# import chart_studio.plotly as py
# from plotly.graph_objects import *
# # py.sign_in('username', 'api_key')
# import plotly.graph_objects as go

# trace1 = go.Choropleth(
#     z=[16361125.0, 80590675.0, 45878500.0, 142326550.0, 891324075.0, 139447350.0, 99382550.0, 16022675.0, 18608750.0,
#        423257500.0, 217453100.0, 32817575.0, 264429975.0, 106329475.0, 56531625.0, 59884500.0, 77991300.0,
#        151888350.0, 160386200.0, 8092775.0, 166060275.0, 116009600.0, 100131525.0, 38427250.0, 16467725.0,
#        182458925.0, 7447300.0, 17027650.0, 31202825.0, 244526800.0, 35603000.0, 84099025.0, 508856550.0,
#        211130650.0, 60860200.0, 69877175.0, 226444700.0, 27194800.0, 76763600.0, 11814875.0, 103152650.0,
#        557716625.0, 42769125.0, 194949075.0, 12974450.0, 138185650.0, 82637750.0, 29911400.0, 13874375.0],
#     colorscale='YlOrRd',
#     autocolorscale=False,
#     reversescale=False,
#     text=["AK", "AL", "AR", "AZ", "CA", "CO", "CT", "DC", "DE", "FL", "GA", "HI", "IL", "IN", "KS", "KY", "LA", "MA", "MD",
#           "ME", "MI", "MN", "MO", "MS", "MT", "NC", "ND", "NE", "NH", "NJ", "NM", "NV", "NY", "OH", "OK", "OR", "PA",
#           "RI", "SC", "SD", "TN", "TX", "UT", "VA", "VT", "WA", "WI", "WV", "WY"],
#     zmin=0,
#     zmax=1000000000,
#     marker_line_color='rgb(180,180,180)',
#     marker_line_width=0.5,
#     colorbar=dict(
#         title='Loan Amount',
#         tickprefix='$',
#         dtick=1000000
#     ),
#     locationmode='USA-states',
#     locations=["AK", "AL", "AR", "AZ", "CA", "CO", "CT", "DC", "DE", "FL", "GA", "HI", "IL", "IN", "KS", "KY", "LA", "MA", "MD",
#           "ME", "MI", "MN", "MO", "MS", "MT", "NC", "ND", "NE", "NH", "NJ", "NM", "NV", "NY", "OH", "OK", "OR", "PA",
#           "RI", "SC", "SD", "TN", "TX", "UT", "VA", "VT", "WA", "WI", "WV", "WY"],
# )
# trace2 = {
#   "type": "choropleth",
#   "z": [61500.0, 199725.0, 72150.0, 462100.0, 4401175.0, 503800.0, 413700.0, 111000.0, 74125.0, 1349125.0, 849650.0, 66800.0, 90550.0, 72350.0, 801700.0, 183125.0, 127650.0, 107450.0, 583075.0, 514500.0, 452775.0, 342725.0, 266250.0, 86575.0, 71400.0, 384875.0, 38550.0, 105275.0, 861075.0, 153775.0, 249250.0, 1655750.0, 692075.0, 103225.0, 181650.0, 584900.0, 135025.0, 151375.0, 10575.0, 222125.0, 1606000.0, 180325.0, 878250.0, 48000.0, 442275.0, 160925.0, 9000.0],
#   "marker": {"line": {
#       "color": "rgb(180,180,180)",
#       "width": 0.5
#     }},
#   "text": ["AK", "AL", "AR", "AZ", "CA", "CO", "CT", "DC", "DE", "FL", "GA", "HI", "IA", "ID", "IL", "KS", "KY", "LA", "MA", "MD", "MI", "MN", "MO", "MS", "MT", "NC", "NE", "NH", "NJ", "NM", "NV", "NY", "OH", "OK", "OR", "PA", "RI", "SC", "SD", "TN", "TX", "UT", "VA", "VT", "WA", "WI", "WV"],
#   "visible": False,
#   "colorbar": {
#     "title": "Loan Amount",
#     "dtick": 1
#   },
#   "locationmode": "USA-states",
#   "locations": ["AK", "AL", "AR", "AZ", "CA", "CO", "CT", "DC", "DE", "FL", "GA", "HI", "IA", "ID", "IL", "KS", "KY", "LA", "MA", "MD", "MI", "MN", "MO", "MS", "MT", "NC", "NE", "NH", "NJ", "NM", "NV", "NY", "OH", "OK", "OR", "PA", "RI", "SC", "SD", "TN", "TX", "UT", "VA", "VT", "WA", "WI", "WV"],
#   "reversescale": False,
#   "autocolorscale": True
# }
# trace3 = {
#   "type": "choropleth",
#   "z": [112325.0, 492125.0, 251500.0, 1238075.0, 9217625.0, 1106600.0, 960575.0, 432425.0, 232800.0, 3661725.0, 1774800.0, 159325.0, 2224775.0, 458350.0, 327400.0, 438825.0, 2057875.0, 1455075.0, 1131475.0, 725250.0, 660275.0, 97875.0, 52350.0, 208850.0, 2440250.0, 277575.0, 647725.0, 5161950.0, 1699950.0, 345500.0, 508575.0, 2314400.0, 243950.0, 640125.0, 57100.0, 3661125.0, 323300.0, 2009175.0, 37700.0, 1100150.0, 603100.0, 221900.0, 156425.0],
#   "marker": {"line": {
#       "color": "rgb(180,180,180)",
#       "width": 0.5
#     }},
#   "text": ["AK", "AL", "AR", "AZ", "CA", "CO", "CT", "DC", "DE", "FL", "GA", "HI", "IL", "KS", "KY", "LA", "MA", "MD", "MI", "MN", "MO", "MS", "MT", "NH", "NJ", "NM", "NV", "NY", "OH", "OK", "OR", "PA", "RI", "SC", "SD", "TX", "UT", "VA", "VT", "WA", "WI", "WV", "WY"],
#   "visible": False,
#   "colorbar": {
#     "title": "Loan Amount",
#     "dtick": 1
#   },
#   "locationmode": "USA-states",
#   "locations": ["AK", "AL", "AR", "AZ", "CA", "CO", "CT", "DC", "DE", "FL", "GA", "HI", "IL", "KS", "KY", "LA", "MA", "MD", "MI", "MN", "MO", "MS", "MT", "NH", "NJ", "NM", "NV", "NY", "OH", "OK", "OR", "PA", "RI", "SC", "SD", "TX", "UT", "VA", "VT", "WA", "WI", "WV", "WY"],
#   "reversescale": False,
#   "autocolorscale": True
# }
# trace4 = {
#   "type": "choropleth",
#   "z": [224000.0, 1546600.0, 791375.0, 2713050.0, 23760550.0, 2975400.0, 2647600.0, 768850.0, 470300.0, 8682375.0, 4802850.0, 460450.0, 9600.0, 5709675.0, 296400.0, 962900.0, 1331075.0, 5091975.0, 3707825.0, 2697500.0, 2004300.0, 2444200.0, 189100.0, 958425.0, 611950.0, 6598125.0, 671800.0, 1304175.0, 13506275.0, 3705400.0, 932650.0, 1444050.0, 5412950.0, 583800.0, 1403025.0, 150750.0, 9566550.0, 817950.0, 4878850.0, 123550.0, 2502325.0, 1659125.0, 588225.0, 284650.0],
#   "marker": {"line": {
#       "color": "rgb(180,180,180)",
#       "width": 0.5
#     }},
#   "text": ["AK", "AL", "AR", "AZ", "CA", "CO", "CT", "DC", "DE", "FL", "GA", "HI", "IA", "IL", "KS", "KY", "LA", "MA", "MD", "MI", "MN", "MO", "MT", "NC", "NH", "NJ", "NM", "NV", "NY", "OH", "OK", "OR", "PA", "RI", "SC", "SD", "TX", "UT", "VA", "VT", "WA", "WI", "WV", "WY"],
#   "visible": False,
#   "colorbar": {
#     "title": "Loan Amount",
#     "dtick": 1
#   },
#   "locationmode": "USA-states",
#   "locations": ["AK", "AL", "AR", "AZ", "CA", "CO", "CT", "DC", "DE", "FL", "GA", "HI", "IA", "IL", "KS", "KY", "LA", "MA", "MD", "MI", "MN", "MO", "MT", "NC", "NH", "NJ", "NM", "NV", "NY", "OH", "OK", "OR", "PA", "RI", "SC", "SD", "TX", "UT", "VA", "VT", "WA", "WI", "WV", "WY"],
#   "reversescale": False,
#   "autocolorscale": True
# }
# trace5 = {
#   "type": "choropleth",
#   "z": [712775.0, 3107725.0, 1583900.0, 5619350.0, 46373300.0, 4858650.0, 5128075.0, 1441550.0, 601500.0, 18438675.0, 9025850.0, 1271350.0, 10268775.0, 2229225.0, 2470300.0, 2865275.0, 8097000.0, 6894075.0, 4472225.0, 3705200.0, 4453175.0, 6000.0, 642375.0, 7783425.0, 1207175.0, 12837575.0, 983600.0, 3453700.0, 24081825.0, 8112050.0, 2177950.0, 2822350.0, 9023825.0, 1026175.0, 3081025.0, 410600.0, 28000.0, 18893100.0, 1692275.0, 9149450.0, 302450.0, 5506650.0, 3155100.0, 1182025.0, 507175.0],
#   "marker": {"line": {
#       "color": "rgb(180,180,180)",
#       "width": 0.5
#     }},
#   "text": ["AK", "AL", "AR", "AZ", "CA", "CO", "CT", "DC", "DE", "FL", "GA", "HI", "IL", "KS", "KY", "LA", "MA", "MD", "MI", "MN", "MO", "MS", "MT", "NC", "NH", "NJ", "NM", "NV", "NY", "OH", "OK", "OR", "PA", "RI", "SC", "SD", "TN", "TX", "UT", "VA", "VT", "WA", "WI", "WV", "WY"],
#   "visible": False,
#   "colorbar": {
#     "title": "Loan Amount",
#     "dtick": 1
#   },
#   "locationmode": "USA-states",
#   "locations": ["AK", "AL", "AR", "AZ", "CA", "CO", "CT", "DC", "DE", "FL", "GA", "HI", "IL", "KS", "KY", "LA", "MA", "MD", "MI", "MN", "MO", "MS", "MT", "NC", "NH", "NJ", "NM", "NV", "NY", "OH", "OK", "OR", "PA", "RI", "SC", "SD", "TN", "TX", "UT", "VA", "VT", "WA", "WI", "WV", "WY"],
#   "reversescale": False,
#   "autocolorscale": True
# }
# trace6 = {
#   "type": "choropleth",
#   "z": [2778500.0, 9731725.0, 5343300.0, 14889250.0, 123433375.0, 13436675.0, 11837625.0, 2211200.0, 1656575.0, 50439525.0, 22453175.0, 4382575.0, 28813000.0, 358575.0, 6978450.0, 6323875.0, 9128150.0, 20252100.0, 16848275.0, 15922075.0, 11643450.0, 11123800.0, 4000.0, 2072350.0, 20614400.0, 21250.0, 3352125.0, 29079350.0, 4007625.0, 10343175.0, 69275225.0, 20812825.0, 5697300.0, 8183725.0, 22906825.0, 3082000.0, 8467375.0, 1431725.0, 59469150.0, 5006175.0, 23834550.0, 1643175.0, 16127900.0, 8302350.0, 2964475.0, 1726725.0],
#   "marker": {"line": {
#       "color": "rgb(180,180,180)",
#       "width": 0.5
#     }},
#   "text": ["AK", "AL", "AR", "AZ", "CA", "CO", "CT", "DC", "DE", "FL", "GA", "HI", "IL", "IN", "KS", "KY", "LA", "MA", "MD", "MI", "MN", "MO", "MS", "MT", "NC", "NE", "NH", "NJ", "NM", "NV", "NY", "OH", "OK", "OR", "PA", "RI", "SC", "SD", "TX", "UT", "VA", "VT", "WA", "WI", "WV", "WY"],
#   "visible": False,
#   "colorbar": {
#     "title": "Loan Amount",
#     "dtick": 1
#   },
#   "locationmode": "USA-states",
#   "locations": ["AK", "AL", "AR", "AZ", "CA", "CO", "CT", "DC", "DE", "FL", "GA", "HI", "IL", "IN", "KS", "KY", "LA", "MA", "MD", "MI", "MN", "MO", "MS", "MT", "NC", "NE", "NH", "NJ", "NM", "NV", "NY", "OH", "OK", "OR", "PA", "RI", "SC", "SD", "TX", "UT", "VA", "VT", "WA", "WI", "WV", "WY"],
#   "reversescale": False,
#   "autocolorscale": True
# }
# trace7 = {
#   "type": "choropleth",
#   "z": [6442525.0, 23730200.0, 13654625.0, 44040375.0, 311438625.0, 43801325.0, 31058975.0, 5912125.0, 5284925.0, 122259025.0, 63342575.0, 11975675.0, 7200.0, 9000.0, 79206700.0, 33997925.0, 18794125.0, 17821900.0, 23975950.0, 49350675.0, 48314775.0, 47930775.0, 33589550.0, 30575725.0, 35975.0, 5551425.0, 55099475.0, 17200.0, 9235650.0, 78971825.0, 11298600.0, 27324400.0, 160206425.0, 61908250.0, 18395025.0, 26015975.0, 65692750.0, 7896025.0, 22312825.0, 3873425.0, 29887100.0, 159724025.0, 16104500.0, 64993125.0, 2371725.0, 48848375.0, 24094925.0, 10260375.0, 5354550.0],
#   "marker": {"line": {
#       "color": "rgb(180,180,180)",
#       "width": 0.5
#     }},
#   "text": ["AK", "AL", "AR", "AZ", "CA", "CO", "CT", "DC", "DE", "FL", "GA", "HI", "IA", "ID", "IL", "IN", "KS", "KY", "LA", "MA", "MD", "MI", "MN", "MO", "MS", "MT", "NC", "NE", "NH", "NJ", "NM", "NV", "NY", "OH", "OK", "OR", "PA", "RI", "SC", "SD", "TN", "TX", "UT", "VA", "VT", "WA", "WI", "WV", "WY"],
#   "visible": False,
#   "colorbar": {
#     "title": "Loan Amount",
#     "dtick": 1
#   },
#   "locationmode": "USA-states",
#   "locations": ["AK", "AL", "AR", "AZ", "CA", "CO", "CT", "DC", "DE", "FL", "GA", "HI", "IA", "ID", "IL", "IN", "KS", "KY", "LA", "MA", "MD", "MI", "MN", "MO", "MS", "MT", "NC", "NE", "NH", "NJ", "NM", "NV", "NY", "OH", "OK", "OR", "PA", "RI", "SC", "SD", "TN", "TX", "UT", "VA", "VT", "WA", "WI", "WV", "WY"],
#   "reversescale": False,
#   "autocolorscale": True
# }
# trace8 = {
#   "type": "choropleth",
#   "z": [10285300.0, 45167175.0, 25833125.0, 78694450.0, 488123300.0, 74817350.0, 51439700.0, 9980650.0, 9981125.0, 220137275.0, 114642800.0, 18382550.0, 6725.0, 7000.0, 147590100.0, 61663850.0, 30912975.0, 34208550.0, 41046825.0, 85224050.0, 87121425.0, 29850.0, 87800700.0, 60713375.0, 55070575.0, 18391075.0, 10197975.0, 94354950.0, 17581550.0, 139586200.0, 20619600.0, 45016500.0, 293232400.0, 114606675.0, 31491175.0, 40318600.0, 123262525.0, 14890425.0, 44817100.0, 7122525.0, 58688950.0, 298467650.0, 24890575.0, 110375675.0, 7669800.0, 76440825.0, 44642175.0, 19135575.0, 9148875.0],
#   "marker": {"line": {
#       "color": "rgb(180,180,180)",
#       "width": 0.5
#     }},
#   "text": ["AK", "AL", "AR", "AZ", "CA", "CO", "CT", "DC", "DE", "FL", "GA", "HI", "IA", "ID", "IL", "IN", "KS", "KY", "LA", "MA", "MD", "ME", "MI", "MN", "MO", "MS", "MT", "NC", "NH", "NJ", "NM", "NV", "NY", "OH", "OK", "OR", "PA", "RI", "SC", "SD", "TN", "TX", "UT", "VA", "VT", "WA", "WI", "WV", "WY"],
#   "visible": False,
#   "colorbar": {
#     "title": "Loan Amount",
#     "dtick": 1
#   },
#   "locationmode": "USA-states",
#   "locations": ["AK", "AL", "AR", "AZ", "CA", "CO", "CT", "DC", "DE", "FL", "GA", "HI", "IA", "ID", "IL", "IN", "KS", "KY", "LA", "MA", "MD", "ME", "MI", "MN", "MO", "MS", "MT", "NC", "NH", "NJ", "NM", "NV", "NY", "OH", "OK", "OR", "PA", "RI", "SC", "SD", "TN", "TX", "UT", "VA", "VT", "WA", "WI", "WV", "WY"],
#   "reversescale": False,
#   "autocolorscale": True
# }
# trace9 = {
#   "type": "choropleth",
#   "z": [16361125.0, 80590675.0, 45878500.0, 142326550.0, 891324075.0, 139447350.0, 99382550.0, 16022675.0, 18608750.0, 423257500.0, 217453100.0, 32817575.0, 264429975.0, 106329475.0, 56531625.0, 59884500.0, 77991300.0, 151888350.0, 160386200.0, 8092775.0, 166060275.0, 116009600.0, 100131525.0, 38427250.0, 16467725.0, 182458925.0, 7447300.0, 17027650.0, 31202825.0, 244526800.0, 35603000.0, 84099025.0, 508856550.0, 211130650.0, 60860200.0, 69877175.0, 226444700.0, 27194800.0, 76763600.0, 11814875.0, 103152650.0, 557716625.0, 42769125.0, 194949075.0, 12974450.0, 138185650.0, 82637750.0, 29911400.0, 13874375.0],
#   "marker": {"line": {
#       "color": "rgb(180,180,180)",
#       "width": 0.5
#     }},
#   "text": ["AK", "AL", "AR", "AZ", "CA", "CO", "CT", "DC", "DE", "FL", "GA", "HI", "IL", "IN", "KS", "KY", "LA", "MA", "MD", "ME", "MI", "MN", "MO", "MS", "MT", "NC", "ND", "NE", "NH", "NJ", "NM", "NV", "NY", "OH", "OK", "OR", "PA", "RI", "SC", "SD", "TN", "TX", "UT", "VA", "VT", "WA", "WI", "WV", "WY"],
#   "visible": False,
#   "colorbar": {
#     "title": "Loan Amount",
#     "dtick": 1
#   },
#   "locationmode": "USA-states",
#   "locations": ["AK", "AL", "AR", "AZ", "CA", "CO", "CT", "DC", "DE", "FL", "GA", "HI", "IL", "IN", "KS", "KY", "LA", "MA", "MD", "ME", "MI", "MN", "MO", "MS", "MT", "NC", "ND", "NE", "NH", "NJ", "NM", "NV", "NY", "OH", "OK", "OR", "PA", "RI", "SC", "SD", "TN", "TX", "UT", "VA", "VT", "WA", "WI", "WV", "WY"],
#   "reversescale": False,
#   "autocolorscale": True
# }
# trace10 = {
#   "type": "choropleth",
#   "z": [61700.0, 7600.0, 126900.0, 73225.0, 146225.0, 87950.0, 8000.0, 6000.0, 763850.0, 364800.0, 23750.0, 144075.0, 11600.0, 7000.0, 42825.0, 339375.0, 214525.0, 9200.0, 142250.0, 52400.0, 223650.0, 50400.0, 50500.0, 351800.0, 47400.0, 21625.0, 965575.0, 7500.0, 52150.0, 25000.0, 2825.0, 25350.0, 71925.0, 153900.0, 2500.0, 121725.0, 150400.0, 20000.0],
#   "marker": {"line": {
#       "color": "rgb(180,180,180)",
#       "width": 0.5
#     }},
#   "text": ["AL", "AR", "AZ", "CA", "CO", "CT", "DC", "DE", "FL", "GA", "IL", "IN", "KS", "KY", "LA", "MA", "MD", "ME", "MO", "MT", "NC", "NE", "NH", "NJ", "NM", "NV", "NY", "OH", "SC", "SD", "TN", "TX", "UT", "VA", "VT", "WA", "WI", "WY"],
#   "visible": False,
#   "colorbar": {
#     "title": "Loan Amount",
#     "dtick": 1
#   },
#   "locationmode": "USA-states",
#   "locations": ["AL", "AR", "AZ", "CA", "CO", "CT", "DC", "DE", "FL", "GA", "IL", "IN", "KS", "KY", "LA", "MA", "MD", "ME", "MO", "MT", "NC", "NE", "NH", "NJ", "NM", "NV", "NY", "OH", "SC", "SD", "TN", "TX", "UT", "VA", "VT", "WA", "WI", "WY"],
#   "reversescale": False,
#   "autocolorscale": True
# }
# data = Data([trace1, trace2, trace3, trace4, trace5, trace6, trace7, trace8, trace9, trace10])
# layout = {
#   "geo": {
#     "scope": "usa",
#     "showframe": False,
#     "projection": {"type": "mercator"},
#     "showcoastlines": True
#   },
#   "title": "Loan Amount by States<br>Source:            <a href=\"https://www.kaggle.com/wendykan/lending-club-loan-data/data\">            Kaggle</a>",
#   "updatemenus": [
#     {"buttons": [
#         {
#           "args": [
#             {"visible": [False, True, False, False, False, False, False, False, False, False]}
#           ],
#           "label": 2008,
#           "method": "update"
#         },
#         {
#           "args": [
#             {"visible": [False, False, True, False, False, False, False, False, False, False]}
#           ],
#           "label": 2009,
#           "method": "update"
#         },
#         {
#           "args": [
#             {"visible": [False, False, False, True, False, False, False, False, False, False]}
#           ],
#           "label": 2010,
#           "method": "update"
#         },
#         {
#           "args": [
#             {"visible": [False, False, False, False, True, False, False, False, False, False]}
#           ],
#           "label": 2011,
#           "method": "update"
#         },
#         {
#           "args": [
#             {"visible": [False, False, False, False, False, True, False, False, False, False]}
#           ],
#           "label": 2012,
#           "method": "update"
#         },
#         {
#           "args": [
#             {"visible": [False, False, False, False, False, False, True, False, False, False]}
#           ],
#           "label": 2013,
#           "method": "update"
#         },
#         {
#           "args": [
#             {"visible": [False, False, False, False, False, False, False, True, False, False]}
#           ],
#           "label": 2014,
#           "method": "update"
#         },
#         {
#           "args": [
#             {"visible": [False, False, False, False, False, False, False, False, True, False]}
#           ],
#           "label": 2015,
#           "method": "update"
#         },
#         {
#           "args": [
#             {"visible": [False, False, False, False, False, False, False, False, False, True]}
#           ],
#           "label": 2007,
#           "method": "update"
#         },
#         {
#           "args": [
#             {"visible": [True, False, False, False, False, False, False, False, False, False]}
#           ],
#           "label": "reset",
#           "method": "update"
#         }
#       ]},
#     {
#       "direction": "down",
#       "showactive": True
#     }
#   ]
# }
# import plotly.io as pio

# # # Generate the figure and plot
# # fig = Figure(data=[trace1], layout=layout)


# fig = Figure(data=data, layout=layout)
# py.plot(fig)
# # Save the plot as an image file
# # pio.write_html(fig,"/content/try.html")
